variables:
  - &scw-secrets
    - SCW_ACCESS_KEY
    - SCW_SECRET_KEY
    - SCW_DEFAULT_ORGANIZATION_ID
  - &setup-scw-s3 "wget https://github.com/scaleway/scaleway-cli/releases/download/v2.5.1/scaleway-cli_2.5.1_linux_amd64 && mv scaleway-cli_2.5.1_linux_amd64 scaleway-cli && chmod +x scaleway-cli && ./scaleway-cli object config install type=rclone"

  - &setup-hex "mix local.hex --force &&  mix local.rebar --force"
  - &build-on
    when:
      event:
      - push
      - tag
      branch:
      - develop
      - stable
      - refs/tags/v*
      - refs/tags/stable-*  
      - docker-build
  - &tag-build 'export BUILD_TAG=$${CI_COMMIT_TAG:-"$CI_COMMIT_BRANCH"} && export PLEROMA_BUILD_BRANCH=$BUILD_TAG'

  - &clean "(rm -rf release || true) && (rm -rf _build || true) && (rm -rf /root/.mix) && (rm scaleway-cli || true) && (mix deps.clean --all || true)"


pipeline:
  glibc:
    image: hexpm/elixir:1.13.4-erlang-24.3.4.2-ubuntu-focal-20211006
    <<: *build-on
    secrets: *scw-secrets
    environment:
      MIX_ENV: prod
    commands:
      - apt-get update && apt-get install -y cmake libmagic-dev rclone zip imagemagick libmagic-dev git
      - *clean
      - *setup-scw-s3
      - echo "import Mix.Config" > config/prod.secret.exs
      - *setup-hex
      - *tag-build
      - mix deps.get --only prod
      - mix release --path release
      - zip akkoma-${tag}.zip -r release
      - rclone copyto akkoma-${tag}.zip scaleway:akkoma-updates/$BUILD_TAG/akkoma-${tag}.zip

  musl:
    image: hexpm/elixir:1.13.4-erlang-24.3.4.2-alpine-3.16.0
    <<: *build-on
    secrets: *scw-secrets
    environment:
      MIX_ENV: prod
    commands:
      - apk add git gcc g++ musl-dev make cmake file-dev rclone wget zip imagemagick
      - *clean
      - *setup-scw-s3
      - *setup-hex
      - *tag-build
      - mix deps.get --only prod
      - mix release --path release
      - zip akkoma-${tag}.zip -r release
      - rclone copyto akkoma-${tag}.zip scaleway:akkoma-updates/$BUILD_TAG/akkoma-${tag}-musl.zip

  docker:
    image: woodpeckerci/plugin-docker-buildx
    <<: *build-on
    secrets: [docker_username, docker_password]
    settings:
      repo: akkoma/akkoma
      dockerfile: Dockerfile
      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
      tag: [latest, alpine]
